AWSTemplateFormatVersion: "2010-09-09"
Description: This is CloudFormation template used to create a S3 bucket following the best pratices to prevent securtiy incidents. Disable Acesss control list (ACLs), Pulic polices reject calls to PUT Bucket policy, IgnorePublicAcls prevent new public ACLs from being set, RestrictPublicBuckets.

Parameters:
  BucketNameParameter:
    Type: String
    Description: 'The bucket name'
  Environment:
    Type: String
    AllowedValues:
      - Development
      - Stage
      - Production
    Description: 'Select the bucket environment'
  KMSKeyArn:
    Type: String
    Description: "KMS Key Arn to encrypt S3 bucket"
    Default: ""
  SSEAlgorithm:
    Type: String
    Description: "Encryption algorithm for KMS"
    AllowedValues:
      - aws:kms
      - AES256    

Mappings:
  EnvironmentToBucketSuffix:
    Development:
      Suffix: 'dev'
    Stage:      
      Suffix: 'stg'
    Production:
      Suffix: 'prd'

Conditions:
  AES256: !Equals [!Ref SSEAlgorithm, "AES256"]

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Join [ '-', [!Ref BucketNameParameter, !FindInMap [EnvironmentToBucketSuffix, !Ref Environment, Suffix]]]
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - !If
          - AES256
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !Ref SSEAlgorithm
            BucketKeyEnabled: true
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !Ref SSEAlgorithm
              KMSMasterKeyID: !Ref KMSKeyArn
            BucketKeyEnabled: true